[2025-08-14T16:58:10.716+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T16:58:10.748+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_athena_pipeline.dbt_deps manual__2025-08-14T16:58:08.940133+00:00 [queued]>
[2025-08-14T16:58:10.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_athena_pipeline.dbt_deps manual__2025-08-14T16:58:08.940133+00:00 [queued]>
[2025-08-14T16:58:10.758+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-14T16:58:10.777+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-08-14 16:58:08.940133+00:00
[2025-08-14T16:58:10.783+0000] {standard_task_runner.py:64} INFO - Started process 49 to run task
[2025-08-14T16:58:10.789+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_athena_pipeline', 'dbt_deps', 'manual__2025-08-14T16:58:08.940133+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dbt_athena_pipeline.py', '--cfg-path', '/tmp/tmpr7sjszvr']
[2025-08-14T16:58:10.791+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask dbt_deps
[2025-08-14T16:58:10.880+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_athena_pipeline.dbt_deps manual__2025-08-14T16:58:08.940133+00:00 [running]> on host fa848d464678
[2025-08-14T16:58:11.032+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='dbt_athena_pipeline' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T16:58:08.940133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T16:58:08.940133+00:00'
[2025-08-14T16:58:11.033+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T16:58:11.076+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T16:58:11.077+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_athena && dbt deps --profiles-dir /opt/***/dbt_athena/profiles']
[2025-08-14T16:58:11.090+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T16:58:11.092+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***/dbt_athena: No such file or directory
[2025-08-14T16:58:11.092+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T16:58:11.093+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T16:58:11.113+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T16:58:11.118+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_athena_pipeline, task_id=dbt_deps, run_id=manual__2025-08-14T16:58:08.940133+00:00, execution_date=20250814T165808, start_date=20250814T165810, end_date=20250814T165811
[2025-08-14T16:58:11.134+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 1.; 49)
[2025-08-14T16:58:11.165+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-14T16:58:11.194+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T16:58:11.200+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
