[2025-08-13T19:44:44.370+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-13T19:44:44.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_pipeline.ctas_orders_summary manual__2025-08-13T19:44:21+00:00 [queued]>
[2025-08-13T19:44:44.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_pipeline.ctas_orders_summary manual__2025-08-13T19:44:21+00:00 [queued]>
[2025-08-13T19:44:44.409+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-13T19:44:44.427+0000] {taskinstance.py:2330} INFO - Executing <Task(AthenaOperator): ctas_orders_summary> on 2025-08-13 19:44:21+00:00
[2025-08-13T19:44:44.434+0000] {standard_task_runner.py:64} INFO - Started process 78 to run task
[2025-08-13T19:44:44.438+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orders_pipeline', 'ctas_orders_summary', 'manual__2025-08-13T19:44:21+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/orders_pipeline.py', '--cfg-path', '/tmp/tmp0hbmovi5']
[2025-08-13T19:44:44.440+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask ctas_orders_summary
[2025-08-13T19:44:44.517+0000] {task_command.py:426} INFO - Running <TaskInstance: orders_pipeline.ctas_orders_summary manual__2025-08-13T19:44:21+00:00 [running]> on host fb6a3d62f72f
[2025-08-13T19:44:44.669+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='orders_pipeline' AIRFLOW_CTX_TASK_ID='ctas_orders_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T19:44:21+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-13T19:44:21+00:00'
[2025-08-13T19:44:44.670+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-13T19:44:44.686+0000] {athena.py:132} INFO - Running Query with params:
	QueryString: 
		
		CREATE TABLE analytics.orders_summary
		WITH (
		  format='PARQUET',
		  external_location='s3://pt-data-lab/processed-data/orders_summary/'
		) AS
		SELECT
		  customer,
		  CAST(order_date AS DATE) AS order_date,
		  COUNT(*)    AS orders,
		  SUM(amount) AS total_amount
		FROM analytics.raw_orders
		GROUP BY customer, CAST(order_date AS DATE);
	QueryExecutionContext: {'Database': 'analytics', 'Catalog': 'AwsDataCatalog'}
	ResultConfiguration: {'OutputLocation': 's3://pt-data-lab/athena-staging/'}
	WorkGroup: primary
[2025-08-13T19:44:44.704+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2025-08-13T19:44:44.705+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-08-13T19:44:45.035+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-13T19:44:46.084+0000] {athena.py:135} INFO - Query execution id: b7b9a850-3f56-4a7b-8e09-bd0797a53a83
[2025-08-13T19:44:46.315+0000] {waiter_with_logging.py:78} INFO - Query execution id: b7b9a850-3f56-4a7b-8e09-bd0797a53a83, Query is still in non-terminal state: RUNNING
[2025-08-13T19:44:57.676+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-13T19:44:57.717+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=orders_pipeline, task_id=ctas_orders_summary, run_id=manual__2025-08-13T19:44:21+00:00, execution_date=20250813T194421, start_date=20250813T194444, end_date=20250813T194457
[2025-08-13T19:44:57.789+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-13T19:44:57.814+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-13T19:44:57.817+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
