[2025-08-15T18:21:09.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-15T18:21:09.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_pipeline.create_external_table_if_not_exists manual__2025-08-15T18:21:07.183393+00:00 [queued]>
[2025-08-15T18:21:09.502+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_pipeline.create_external_table_if_not_exists manual__2025-08-15T18:21:07.183393+00:00 [queued]>
[2025-08-15T18:21:09.503+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-15T18:21:09.538+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): create_external_table_if_not_exists> on 2025-08-15 18:21:07.183393+00:00
[2025-08-15T18:21:09.551+0000] {standard_task_runner.py:64} INFO - Started process 217 to run task
[2025-08-15T18:21:09.562+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orders_pipeline', 'create_external_table_if_not_exists', 'manual__2025-08-15T18:21:07.183393+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/orders_pipeline.py', '--cfg-path', '/tmp/tmp0uzhk72h']
[2025-08-15T18:21:09.565+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask create_external_table_if_not_exists
[2025-08-15T18:21:09.709+0000] {task_command.py:426} INFO - Running <TaskInstance: orders_pipeline.create_external_table_if_not_exists manual__2025-08-15T18:21:07.183393+00:00 [running]> on host e1203d83167e
[2025-08-15T18:21:09.953+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='orders_pipeline' AIRFLOW_CTX_TASK_ID='create_external_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-08-15T18:21:07.183393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-15T18:21:07.183393+00:00'
[2025-08-15T18:21:09.954+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-15T18:21:10.009+0000] {credentials.py:1217} INFO - Found credentials in environment variables.
[2025-08-15T18:21:13.070+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-15T18:21:13.073+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-15T18:21:13.101+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=orders_pipeline, task_id=create_external_table_if_not_exists, run_id=manual__2025-08-15T18:21:07.183393+00:00, execution_date=20250815T182107, start_date=20250815T182109, end_date=20250815T182113
[2025-08-15T18:21:13.179+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-15T18:21:13.245+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-15T18:21:13.249+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
